Apply black formatting (#2115)
* Testing black on ui/

* Applying black on docstores

* Add latest docstring and tutorial changes

* Create a single GH action for Black and docs to reduce commit noise to the minimum, slightly refactor the OpenAPI action too

* Remove comments

* Relax constraints on pydoc-markdown

* Split temporary black from the docs. Pydoc-markdown was obsolete and needs a separate PR to upgrade

* Fix a couple of bugs

* Add a type: ignore that was missing somehow

* Give path to black

* Apply Black

* Apply Black

* Relocate a couple of type: ignore

* Update documentation

* Make Linux CI run after applying Black

* Triggering Black

* Apply Black

* Remove dependency, does not work well

* Remove manually double trailing commas

* Update documentation

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/blacken.yml b/.github/workflows/blacken.yml
--- a/.github/workflows/blacken.yml
+++ b/.github/workflows/blacken.yml
@@ -1,10 +1,10 @@
-name: Generate OpenAPI Specs
+name: Code Style
 
 on:
-  workflow_dispatch:
   push:
-    paths:
-      - "rest_api/**"
+    branches-ignore:
+      - master
+      - benchmarks
 
 jobs:
   build:
@@ -14,23 +14,21 @@ jobs:
       - uses: actions/checkout@v2
         with:
           persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
-          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
 
-      - name: Set up Python 3.8.10
+      - name: Set up Python 3.7
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8.10
+          python-version: 3.7
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          python -m pip install rest_api/
-
-      # Generates the OpenAPI specs file to be used on the documentation website
-      - name: Generate OpenAPI Specs
-        run: |
-          cd docs/_src/api/openapi/
-          python generate_openapi_specs.py
+          pip install black
+      
+      # Apply black on the entire codebase
+      - name: Blacken
+        run: python3 -m black .
 
       - name: Commit files
         run: |
@@ -38,8 +36,8 @@ jobs:
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git add .
-          git commit -m "Update OpenAPI Specs" -a || echo "No changes to commit"
-
+          git commit -m "Apply Black" -a || echo "No changes to commit"
+      
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
