Add images testing in CI

diff --git a/.github/workflows/docker_release.yml b/.github/workflows/docker_release.yml
--- a/.github/workflows/docker_release.yml
+++ b/.github/workflows/docker_release.yml
@@ -73,6 +73,26 @@ jobs:
           # Remove image after test to avoid filling the GitHub runner and prevent its failure
           docker rmi "deepset/haystack:$TAG"
 
+      - name: Test non-inference image
+        if: contains(matrix.target, 'inference') != true
+        run: |
+          PLATFORM="linux/amd64"
+          TORCH_INSTALLED=$(docker run --platform "$PLATFORM" --rm "deepset/haystack:$TAG" pip list | grep torch)
+          [[ "$TORCH_INSTALLED" = "" ]] || echo "::error 'Pytorch is not installed in deepset/haystack:$TAG image for $PLATFORM'"
+
+          PLATFORM="linux/arm64"
+          [[ "$TORCH_INSTALLED" = "" ]] || echo "::error 'Pytorch is not installed in deepset/haystack:$TAG image for $PLATFORM'"
+
+      - name: Test inference image
+        if: contains(matrix.target, 'inference')
+        run: |
+          PLATFORM="linux/amd64"
+          TORCH_INSTALLED=$(docker run --platform "$PLATFORM" --rm "deepset/haystack:$TAG" pip list | grep torch)
+          [[ "$TORCH_INSTALLED" != "" ]] || echo "::error 'Pytorch is installed in deepset/haystack:$TAG image for $PLATFORM'"
+
+          PLATFORM="linux/arm64"
+          [[ "$TORCH_INSTALLED" != "" ]] || echo "::error 'Pytorch is installed in deepset/haystack:$TAG image for $PLATFORM'"
+
       - name: Build api images
         uses: docker/bake-action@v2
         env:
@@ -82,6 +102,36 @@ jobs:
           workdir: docker
           targets: ${{ matrix.target }}
           push: true
+
+      - name: Test inference API invocation
+        if: contains(matrix.target, 'inference')
+        env:
+          SERPERDEV_API_KEY: ${{ secrets.SERPERDEV_API_KEY }}
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+        run: |
+          TAG="${{ matrix.target }}-${{ steps.meta.outputs.version }}"
+
+          PLATFORMS=("linux/amd64" "linux/arm64")
+          for PLATFORM in "${PLATFORMS[@]}"; do
+            docker run --name test-container -d \
+              --platform "$PLATFORM" \
+              -e PIPELINE_YAML_PATH=/opt/venv/lib/python3.10/site-packages/rest_api/pipeline/pipelines_web_lfqa.haystack-pipeline.yaml \
+              -e "RETRIEVER_PARAMS_API_KEY=$SERPERDEV_API_KEY" \
+              -e "PROMPTNODE_PARAMS_API_KEY=$OPENAI_API_KEY" \
+              -p 8080:8000 "deepset/haystack:$TAG"
+
+            I=0
+            until docker logs test-container 2>&1 | grep "Uvicorn running"; do
+              echo "Waiting"
+              sleep 2
+              ((I++)) && ((I==100)) && echo "::error 'Timeout waiting for Uvicorn to start using deepset/haystack:$TAG image for $PLATFORM'"
+            done
+
+            RESULT=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"query\": \"Where in Europe, should I live?\"}" http://localhost:8080/query)
+            [[ -n "$RESULT" ]] || echo "::error 'No response from inference API using deepset/haystack:$TAG image for $PLATFORM'"
+
+            docker rm -f test-container
+          done
 
       - name: Get latest version of Haystack
         id: latest-version
