try monitor

diff --git a/.github/workflows/docs_search_sync.yml b/.github/workflows/docs_search_sync.yml
--- a/.github/workflows/docs_search_sync.yml
+++ b/.github/workflows/docs_search_sync.yml
@@ -4,6 +4,8 @@ on:
   workflow_dispatch: # Activate this workflow manually
   schedule:
     - cron: "0 1 * * *"
+  # TODO: remove this
+  pull_request:
 
 # Running this workflow multiple times in parallel can cause issues with files uploads and deletions.
 concurrency:
@@ -29,6 +31,11 @@ jobs:
         with:
           python-version: "3.12"
 
+      - name: try failure
+        run: |
+          echo "This is a workflow failure"
+          exit 1
+
       - name: Install Docusaurus and build docs-website
         working-directory: docs-website
         run: |
@@ -43,3 +50,23 @@ jobs:
           DEEPSET_WORKSPACE_DOCS_SEARCH: ${{ secrets.DEEPSET_WORKSPACE_DOCS_SEARCH }}
           DEEPSET_API_KEY_DOCS_SEARCH: ${{ secrets.DEEPSET_API_KEY_DOCS_SEARCH }}
         run: python ./.github/utils/docs_search_sync.py
+
+      - name: Send event to Datadog for nightly failures
+        if: failure() && github.event_name == 'schedule'
+        uses: masci/datadog@v1
+        with:
+          api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
+          api-url: https://api.datadoghq.eu
+          events: |
+            - title: "${{ github.workflow }} workflow"
+              text: "Job ${{ github.job }} in branch ${{ github.ref_name }}"
+              alert_type: "error"
+              source_type_name: "Github"
+              host: ${{ github.repository_owner }}
+              tags:
+                - "project:${{ github.repository }}"
+                - "job:${{ github.job }}"
+                - "run_id:${{ github.run_id }}"
+                - "workflow:${{ github.workflow }}"
+                - "branch:${{ github.ref_name }}"
+                - "url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
