Add code and docs check

diff --git a/.github/workflows/linux_ci.yml b/.github/workflows/linux_ci.yml
--- a/.github/workflows/linux_ci.yml
+++ b/.github/workflows/linux_ci.yml
@@ -126,6 +126,84 @@ jobs:
           pylint -ry rest_api/
           pylint -ry ui/
 
+  
+  code-and-docs-check:
+    needs: build-cache
+    runs-on: ubuntu-latest
+
+    steps:
+      - run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
+
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.7
+
+      - name: Cache Python
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.pythonLocation }}
+          key: linux-${{ env.date }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/setup.cfg') }}-${{ hashFiles('**/pyproject.toml') }}
+
+      - name: Install Dependencies (on cache miss only)
+        # The cache might miss during the execution of an action: there should always be a fallback step to
+        # rebuild it in case it goes missing
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: |
+          pip install --upgrade pip
+          pip install .[test]
+          pip install rest_api/
+          pip install ui/
+          pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
+          echo "=== pip freeze ==="
+          pip freeze
+          
+      # Apply Black on the entire codebase
+      - name: Blacken
+        run: black .
+
+      # Convert the Jupyter notebooks into markdown tutorials
+      - name: Generate Tutorials
+        run: |
+          cd docs/_src/tutorials/tutorials/
+          python3 convert_ipynb.py
+
+      # Generate markdown files from the docstrings with pydoc-markdown
+      - name: Generate Docstrings
+        run: |
+          set -e   # Fails on any error in the following loop
+          cd docs/_src/api/api/
+          for file in ../pydoc/* ; do
+            echo "Processing" $file
+            pydoc-markdown "$file"
+          done
+
+      # Generates the OpenAPI specs file to be used on the documentation website
+      - name: Generate OpenAPI Specs
+        run: |
+          pip install rest_api/
+          cd docs/_src/api/openapi/
+          python generate_openapi_specs.py
+
+      # Generates a new JSON schema for the pipeline YAML validation
+      - name: Generate JSON schema for pipelines
+        run: python ./.github/utils/generate_json_schema.py
+      
+      # If there is anything to commit, fail
+      # Note: this CI action mirrors autoformat.yml, with the difference that it
+      # runs on Haystack's end. If the contributor hasn't run autoformat.yml, then this
+      # check will fail.
+      - name: Check git status
+        run: |
+          if [[ `git status --porcelain` ]]; then
+            git status
+            exit 1
+          fi
+
 
   prepare-matrix:
     needs: build-cache
