try using one workflow

diff --git a/.github/workflows/slow.yml b/.github/workflows/slow.yml
--- a/.github/workflows/slow.yml
+++ b/.github/workflows/slow.yml
@@ -1,6 +1,12 @@
 # If you change this name also do it in slow_skipper.yml and ci_metrics.yml
 name: Slow Integration Tests
 
+env:
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  HF_API_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}
+  PYTHON_VERSION: "3.9"
+  HATCH_VERSION: "1.14.1"
+
 on:
   workflow_dispatch: # Activate this workflow manually
   schedule:
@@ -14,30 +20,42 @@ on:
       - opened
       - reopened
       - synchronize
-    paths:
-      # Keep the list in sync with the paths defined in the `slow_skipper.yml` workflow
-      - "haystack/components/audio/whisper_local.py"
-      - "haystack/components/converters/tika.py"
-      - "test/components/converters/test_tika_doc_converter.py"
-      - "test/components/audio/test_whisper_local.py"
-
-env:
-  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  HF_API_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}
-  PYTHON_VERSION: "3.9"
-  HATCH_VERSION: "1.14.1"
 
 jobs:
+
+  check_if_changed:
+    name: Check if changed
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: read
+    outputs:
+      code_changes: ${{ steps.changes.outputs.code_changes }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check for changed code
+        id: changes
+        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
+        with:
+          # keep the list in sync with the paths defined in the `tests.yml` workflow and above in this file
+          filters: |
+            code_changes:
+              - "haystack/components/audio/whisper_local.py"
+              - "haystack/components/converters/tika.py"
+              - "test/components/converters/test_tika_doc_converter.py"
+              - "test/components/audio/test_whisper_local.py"
 
   slow-integration-tests-linux:
     name: Slow Tests / ubuntu-latest
     runs-on: ubuntu-latest
+    needs: check_if_changed
+    if: needs.check_if_changed.outputs.code_changes == 'true'
     services:
       tika:
         image: apache/tika:2.9.0.0
         ports:
           - 9998:9998
     steps:
+
       - uses: actions/checkout@v4
 
       - uses: actions/setup-python@v5
@@ -95,6 +113,8 @@ jobs:
     runs-on: macos-latest
     env:
       HAYSTACK_MPS_ENABLED: false
+    needs: check_if_changed
+    if: needs.check_if_changed.outputs.code_changes == 'true'
 
     steps:
       - uses: actions/checkout@v4
@@ -151,6 +171,8 @@ jobs:
   slow-integration-tests-windows:
     name: Slow Tests / windows-latest
     runs-on: windows-latest
+    needs: check_if_changed
+    if: needs.check_if_changed.outputs.code_changes == 'true'
     steps:
       - uses: actions/checkout@v4
 
@@ -207,11 +229,17 @@ jobs:
     # are successful.
     # This way we'll be able to mark only this test as required
     # and skip it accordingly.
+    if: ${{ always() }}
     needs:
       - slow-integration-tests-linux
       - slow-integration-tests-macos
       - slow-integration-tests-windows
     steps:
-      - name: Mark tests as completed
-        run: |
+    - name: Mark tests as completed
+      run: |
+        if [ "${{ needs.slow-integration-tests-linux.result }}" = "failure" ] || [ "${{ needs.slow-integration-tests-macos.result }}" = "failure" ] || [ "${{ needs.slow-integration-tests-windows.result }}" = "failure" ]; then
+          echo "Slow Integration Tests failed!"
+          exit 1
+        else
           echo "Slow Integration Tests completed!"
+        fi
