Move autoformat-check.yml into tests.yml (#2635)

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -654,3 +654,37 @@ jobs:
         pytest ${{ env.PYTEST_PARAMS }} -m "integration and not tika and not graphdb" ${{ env.SUITES_EXCLUDED_FROM_WINDOWS }} test/${{ matrix.folder }} --document_store_type=memory,faiss,elasticsearch
  
  
+  # This CI action mirrors autoformat.yml, with the difference that it
+  # runs on Haystack's end. If the contributor hasn't run autoformat.yml, 
+  # then this check will fail.
+  bot-check:
+    runs-on: ubuntu-latest
+    needs: unit-tests-linux
+    steps:
+
+      - uses: actions/checkout@v2
+            
+      - name: Setup Python
+        uses: ./.github/actions/python_cache/
+
+      - name: Install Dependencies
+        run: |
+          pip install --upgrade pip
+          pip install .[all]
+          pip install rest_api/
+          pip install ui/
+
+      - name: Code and Docs Updates
+        run: ./.github/utils/code_and_docs.sh
+
+      # If there is anything to commit, fail
+      - name: Check status
+        run: |
+          if [[ `git status --porcelain` ]]; then
+            git status
+            echo ""
+            echo "This means that the 'autoformat.yml' action didn't run."
+            echo "Please enable GitHub Action on your fork to pass this check!"
+            echo "See https://github.com/deepset-ai/haystack/blob/master/CONTRIBUTING.md#forks for instructions"
+            exit 1
+          fi
