Try caching the GoT data before running the scripts

diff --git a/.github/workflows/tutorials.yml b/.github/workflows/tutorials.yml
--- a/.github/workflows/tutorials.yml
+++ b/.github/workflows/tutorials.yml
@@ -154,28 +154,42 @@ jobs:
         pip install pygraphviz
         pip install ipython nbformat
 
-    - name: Run notebooks
-      run: |
-        export LAUNCH_GRAPHDB=0
-        set -e   # Fails on any error in the following loop
-        for script in ${{ matrix.script-path }}; do
-          echo ""
-          echo "============================================================="
-          echo "Running $script ..."
-          echo "============================================================="
-          echo ""
-          sudo ${{ env.pythonLocation }}/bin/ipython -c "%run $script.ipynb"
-        done
+    # - name: Run notebooks
+    #   run: |
+    #     export LAUNCH_GRAPHDB=0
+    #     set -e   # Fails on any error in the following loop
+    #     for script in ${{ matrix.script-path }}; do
+    #       echo ""
+    #       echo "============================================================="
+    #       echo "Running $script ..."
+    #       echo "============================================================="
+    #       echo ""
+    #       sudo ${{ env.pythonLocation }}/bin/ipython -c "%run $script.ipynb"
+    #     done
 
     - name: Run scripts
       run: |
         export LAUNCH_GRAPHDB=0
+
+        # Cache the GoT data
+        mkdir data/tutorials
+        wget https://s3.eu-central-1.amazonaws.com/deepset.ai-farm-qa/datasets/documents/wiki_gameofthrones_txt1.zip -q
+        cd data/tutorials
+        unzip wiki_gameofthrones_txt1.zip
+        rm wiki_gameofthrones_txt1.zip
+        find . -name '[1-9][1-9][0-9]_*.txt' -delete
+        find . -name '[0-9]_*.txt' -delete
+        cd ../../
+
+        array=(${{ matrix.script-path }})
+
         set -e   # Fails on any error in the following loop
-        for script in ${{ matrix.script-path }}; do
+        for i in ${!array[@]}; do
           echo ""
           echo "============================================================="
-          echo "Running $script ..."
+          echo "Running ${array[$i]} ..."
           echo "============================================================="
           echo ""
-          python $script.py
+          cp data/tutorials data/tutorial$i
+          python ${array[$i]}.py
         done
